#RELACIONAMENTO ENTRE A TABELA SALA E A TABELA ESPECIALIDADE
ALTER TABLE tbl_sala ADD CONSTRAINT FK_ESPECIALIDADE
FOREIGN KEY (cod_especialidade)
REFERENCES tbl_especialidade (cod_especialidade);

#RELACIONAMENTO ENTRE A TABELA INSUMOS E A TABELA PACIENTE
ALTER TABLE tbl_insumos ADD CONSTRAINT FK_PACIENTE
FOREIGN KEY (cod_paciente)
REFERENCES tbl_paciente (cod_paciente);

#RELACIONAMENTO ENTRE A TABELA MÉDICO EA TABELA ESPECIALIDADE
ALTER TABLE tbl_medico ADD CONSTRAINT FK_ESPECIALIDADE_ESPECIALIDADE
FOREIGN KEY (cod_especialidade)
REFERENCES tbl_especialidade (cod_especialidade);

###RELACIONAMENTO DA TABELA DE AGENDA ##

ALTER TABLE tbl_agenda ADD CONSTRAINT FK_AGENDA_SALA
FOREIGN KEY (cod_sala)
references tbl_sala (cod_sala);

ALTER TABLE tbl_agenda ADD CONSTRAINT FK_AGENDA_MEDICO
FOREIGN KEY (cod_medico)
REFERENCES tbl_medico (cod_medico);

ALTER TABLE tbl_agenda ADD CONSTRAINT FK_AGENDA_PACIENTE
FOREIGN KEY (cod_paciente)
REFERENCES tbl_paciente (cod_paciente);

-- RELACIONAMENTO ENTRE A TABELA INSUMOS E A TABELA PACIENTE
ALTER TABLE tbl_insumos ADD CONSTRAINT FK_AGENDA_INSUMOS
FOREIGN KEY (cod_paciente)
REFERENCES tbl_paciente (cod_paciente);

ALTER TABLE tbl_medico ADD CONSTRAINT FK_AGENDA_ESPECIALIDADES
FOREIGN KEY (cod_especialidade)
REFERENCES tbl_especialidade (cod_especialidade);










