#CRIAÇÃO DE UMA STORE PROCEDURE QUE CONTA E RETORNAA O NUMERO TOTAL DE PACIENTES

DELIMITER $

	CREATE PROCEDURE CONTAGEM_PACIENTES(OUT TOTAL_PACIENTES INT(10))
    
    BEGIN
    
		SELECT COUNT(cod_paciente) INTO TOTAL_PACIENTES  FROM tbl_paciente;
    
    END
    
    $
    
    CALL CONTAGEM_PACIENTES(@TOTAL_PACIENTES);
    
    SELECT @TOTAL_PACIENTES;